spring.application.name=notificationhub

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type=VARCHAR

server.port=${PORT:8081}

openlibrary.api.base-url=https://openlibrary.org